Change  log file location
trustedlogin/vendor pull request #102
Opened 2022-05-27 16:34 UTC by Shelob9

#83

2022-05-27 16:35 UTC, Shelob9 commented
@zackkatz Can you please look at this one? I want to make sure this is the logic you wanted for log file path: 

https://github.com/trustedlogin/vendor/pull/102/files#diff-fea009d1dfdc87fe048f741c4bd7f7ce9e5b2e68ca15bc213dfa8196d51465d5R86

2022-07-11 15:45 UTC, zackkatz requested changes

2022-07-11 15:45 UTC, zackkatz commented on php/Traits/Logger.php
> +        return trailingslashit($upload_dir['baseurl']) . $this->hash . '/trustedlogin.log';
Check for `file_exists()`

2023-02-28 04:07 UTC, merged

2023-02-28 16:24 UTC, Shelob9 commented
This makes the location of log file shown in UI wrong #131