Use invisible POST form for access key redirect
trustedlogin/vendor pull request #82
Opened 2022-05-16 19:24 UTC by Shelob9

Fixes #77

2022-05-16 19:25 UTC, Shelob9 commented
@zackkatz I kept the form, and it submits the same way. BUT, if there is a match, it prints out a form (based on this https://github.com/trustedlogin/trustedlogin-vendor/blob/cb61fdec95552e58a7d572e17e9ecf88cc274657/assets/trustedlogin-access-keys.js#L21-L31) and submits that forms. Seams to work with my test.

2022-05-16 19:46 UTC, zackkatz requested changes

2022-05-16 19:46 UTC, zackkatz commented on admin/components/AccessKeyForm.js
> +    console.log({ action });
To be removed

2022-05-16 19:46 UTC, zackkatz commented on admin/components/Sections.js
> +            submitText={"Rest Keys"}
~Rest~ Reset

2022-05-16 19:46 UTC, zackkatz commented on php/MaybeRedirect.php
> +				"identifier": "F6qvCYIze7i/Ekx4GaYYpNwrlepY8IABPsJFihZD3FRN57eBzx3U3T3HdsRu6cfe9Rr94eihV68dFj3++BNwK7xqrDYJA6Ha+r7vYKwx5vf9tf+/vaLwrro0mLE+9SXcn1cMeFbNQ5v/gz86gu7Qz23QkOsy7mFC2ffU4+dIR8IuOPrdIxGW
Just confirmation that this is placeholder 😉

2022-05-16 19:46 UTC, zackkatz commented on php/MaybeRedirect.php
> +						document.getElementById("trusted-login-redirect-form").submit();
~`trusted-login`~ `trustedlogin`

2022-05-16 19:46 UTC, zackkatz commented on php/MaybeRedirect.php
> +						id="trusted-login-redirect-form"
~`trusted-login`~ `trustedlogin`

2022-05-16 19:50 UTC, zackkatz commented on admin/components/Sections.js
> +                id="rest-keys-button">
~`rest-keys-button`~ `reset-keys-button`

2022-05-17 16:31 UTC, Shelob9 commented
@zackkatz I tested this ZIP file. Ther request to get the access key returned an expected error for invalid secrets (my test site is bad), and it returned expected error.  Can you please retest this, with Gravity View https://github.com/trustedlogin/vendor/blob/af4ea5ad0cb6c47342a1c794900d51fdb4b1476a/trustedlogin-vendor.zip

I'm going to eat lunch and then add better handling of the errors, which are now being caught properly.

2022-05-17 17:41 UTC, Shelob9 commented
@zackkatz [4dc2592](https://github.com/trustedlogin/vendor/pull/82/commits/4dc2592d03ec068c89d85c0bb12268cae8a89c27) impliments the fetch to `loginurl` and then `window.location` redirect to `siteurl`. 

In 4dc2592d03ec068c89d85c0bb12268cae8a89c27 I told fetch to accept cookies set during cross-origin request. That should help. Not sure.

2022-05-17 20:51 UTC, Shelob9 commented
@zackkatz I think this can be merged.

2022-05-17 21:02 UTC, merged